#
server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/blog?serverTimezone=Asia/Seoul
    username: scp
    password: test1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
#        Camel 표기법에 따라 테이블 컬럼이 변경 된다. 예) emailAddress --> email_address
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        사용 한 field 명을 그대로 사용한다.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
      
      
      
      
